services:
  nmos-registry:
    image: nmos-cpp:1.2A-f549712
    container_name: nmos-registry
    hostname: nmos-registry
    domainname: local
    ports:
    - "80-81:80-81"
    - "1883:1883"
    volumes:
    - "./registry.json:/home/registry.json"
    environment:
    - RUN_NODE=FALSE
    networks:
      custom_network:
        ipv4_address: '192.168.1.101'
  nmos-client-1:
    image: nmos-cpp-node:1.2A-f549712
    container_name: nmos-client-1
    hostname: nmos-client-1
    domainname: local
    ports:
    - "84-85:84-85"
    volumes:
    - "./node.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    networks:
      custom_network:
        ipv4_address: '192.168.1.104'
    depends_on:
    - nmos-registry
  nmos-testing:
    image: amwa/nmos-testing:latest
    container_name: nmos-testing
    hostname: nmos-testing
    domainname: local
    entrypoint: |
       /bin/bash -c "/etc/init.d/dbus start;
       /etc/init.d/avahi-daemon start;
       python3 nmos-test.py"
    ports:
    - "5000:5000"
    volumes:
    - "./UserConfig.py:/config/UserConfig.py"
    networks:
      custom_network:
        ipv4_address: '192.168.1.103'
    depends_on:
    - nmos-client-1
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
