version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
