version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
