# https://golangci-lint.run/usage/configuration/
# https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.golangci.yml
linters:
  disable-all: true
  enable:
    - gofmt
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
