#! /bin/bash -xe 
 
echo "running coverity on ${1} stream..."
    abi coverity analyze \
        --debug \
        --aggressiveness-level high \
        --server "${COVERITY_SERVER}" \
        --username "${COVERITY_USR}" \
        --password "${COVERITY_PSW}" \
        --report_output_dir "${WORKSPACE}" \
        --build_command "/usr/bin/build.sh" \
        --stream "${1}"
    cd ${ROOT_DIR}
