#! /bin/bash 

# update report date
sed -i 's|analysis-date:.*|analysis-date: '$(date +%m/%d/%Y)'|g' /usr/bin/report_cfg.yaml
SCRIPT=${1}
STREAM=${2}

function run_coverity(){
    local BUILD_SCRIPT=${1}
    local STREAM=${2}
    abi coverity analyze \
            --debug \
            --aggressiveness-level high \
            --server "${COVERITY_SERVER}" \
            --username "${COVERITY_USR}" \
            --password "${COVERITY_PSW}" \
            --report_output_dir "${WORKSPACE}" \
            --build_command "${BUILD_SCRIPT}" \
            --stream "${STREAM}" \
            --compilers "clang++:g++" \
            --report_yaml "/usr/bin/report_cfg.yaml"
}

export JAVA_HOME=/OWR/Tools/cov_report/2023.3.4/jre/bin/java

. /opt/intel/oneapi/ipp/latest/env/vars.sh
run_coverity "build_onevpl.sh" "sdb-onevpl-patch"
run_coverity "build_mtl.sh" "sdb-mtl-patch"
run_coverity "build_vsr.sh" "sdb-vsr-patch"
run_coverity "build_ffmpeg.sh" "sdb-ffmpeg-patch"
exit 0
