# 
# SPDX-FileCopyrightText: Copyright (c) 2024 Intel Corporation
# 
# SPDX-License-Identifier: BSD-3-Clause
# 

apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-bcs-config
  namespace: bcs
data:
  config.yaml: |
    k8s: true
    definition:
      meshAgent:
        image: "mcm/mesh-agent:latest"
        restPort: 8100
        grpcPort: 50051
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
        scheduleOnNode: ["node-role.kubernetes.io/worker=true"]
      mediaProxy:
        image: mcm/media-proxy:latest
        command: ["media-proxy"]
        args: ["-d", "0000:ca:11.0", "-i", $(POD_IP)]
        grpcPort: 8001
        sdkPort: 8002
        requests:
          cpu: "2"
          memory: "8Gi"
          hugepages-1Gi: "1Gi"
          hugepages-2Mi: "2Gi"
        limits:
          cpu: "2"
          memory: "8Gi"
          hugepages-1Gi: "1Gi"
          hugepages-2Mi: "2Gi"
        volumes:
          memif: /tmp/mcm/memif
          vfio: /dev/vfio
          cache-size: 4Gi
        pvHostPath: /var/run/imtl
        pvStorageClass: manual
        pvStorage: 1Gi
        pvcAssignedName: mtl-pvc
        pvcStorage: 1Gi
        scheduleOnNode: ["node-role.kubernetes.io/worker=true"]
      mtlManager:
        image:  mtl-manager:latest
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
        volumes:
          imtlHostPath: /var/run/imtl
          bpfPath: /sys/fs/bpf
