# 
# SPDX-FileCopyrightText: Copyright (c) 2024 Intel Corporation
# 
# SPDX-License-Identifier: BSD-3-Clause
# 

apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-bcs-config
  namespace: bcs
data:
  config.yaml: |
    k8s: true
    definition:
      meshAgent:
        image: "mesh-agent:latest"
        restPort: 8100
        grpcPort: 50051
      mediaProxy:
        image: mcm/media-proxy:latest
        command: ["media-proxy"]
        args: ["-d", "kernel:eth0", "-i", "$(POD_IP)"]
        grpcPort: 8001
        sdkPort: 8002
        volumes:
          memif: /tmp/mcm/memif
          vfio: /dev/vfio
        pvHostPath: /var/run/imtl
        pvStorageClass: manual
        pvStorage: 1Gi
        pvcStorage: 1Gi