# 
# SPDX-FileCopyrightText: Copyright (c) 2024 Intel Corporation
# 
# SPDX-License-Identifier: BSD-3-Clause
# 

k8s: false # use in both modes: k8s | docker
configuration: # Configuration should be used only for docker mode
  runOnce:
    mediaProxyAgent:
      imageAndTag: mcm/mesh-agent:latest
      gRPCPort: 50051
      restPort: 8100
      network: 
        enable: false
        name: my_net_801f0
        ip: 192.168.2.1
    mediaProxyMcm:
      imageAndTag: mcm/media-proxy:latest
      interfaceName: eth0
      volumes:
        - /dev/vfio:/dev/vfio
      network: 
        enable: false
        name: my_net_801f0
        ip: 192.168.2.2
  workloadToBeRun:
    ffmpegPipeline:
      name: bcs-ffmpeg-pipeline-rx
      imageAndTag: tiber-broadcast-suite:latest
      gRPCPort: 50053
      sourcePort: 5006
      environmentVariables:
        - "http_proxy="
        - "https_proxy=" 
      volumes:
        videos: /root #for videos
        dri: /usr/lib/x86_64-linux-gnu/dri
        kahawai: /tmp/kahawai_lcore.lock
        devnull: /dev/null
        tmpHugepages: /tmp/hugepages
        hugepages: /hugepages
        imtl: /var/run/imtl
        shm: /dev/shm
      devices:
        vfio: /dev/vfio
        dri: /dev/dri
      network: 
        enable: true
        name: my_net_801f0
        ip: 192.168.2.6
    nmosClient:
      name: bcs-ffmpeg-pipeline-nmos-client-rx
      imageAndTag: tiber-broadcast-suite-nmos-node:latest
      environmentVariables:
        - "http_proxy="
        - "https_proxy=" 
        - "VFIO_PORT_TX=0000:ca:11.0"
        - "VFIO_PORT_RX=0000:ca:11.1"
      nmosConfigPath: /root/NMOS-FFMPEG-DEMO/refactor-nmos/tests
      nmosConfigFileName: intel-node-rx.json
      network: 
        enable: true
        name: my_net_801f0
        ip: 192.168.2.7
