#SPDX-FileCopyrightText: Copyright (c) 2024 Intel Corporation
#
#SPDX-License-Identifier: BSD-3-Clause

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-config
data:
  UserConfig.py: |
    from . import Config as CONFIG

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmos-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmos-testing
  template:
    metadata:
      labels:
        app: nmos-testing
    spec:
      containers:
      - name: nmos-testing
        image: amwa/nmos-testing:k8s
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
        - |
          /etc/init.d/dbus start;
          /etc/init.d/avahi-daemon start;
          python3 nmos-test.py
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: testing-config
          mountPath: /config/UserConfig.py
          subPath: UserConfig.py
        resources:
          requests:
            cpu: 1
            memory: 100Mi
          limits:
            cpu: 1
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      volumes:
      - name: testing-config
        configMap:
          name: testing-config

---
apiVersion: v1
kind: Service
metadata:
  name: nmos-testing
spec:
  type: NodePort
  selector:
    app: nmos-testing
  ports:
  - protocol: TCP
    name: nmos-testing-port
    nodePort: 30005
    port: 5000
    targetPort: 5000