name: build-binaries

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  docker:
    name: "Dockerfile build for Intel® Tiber™ Broadcast Suite"
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    permissions:
      contents: read
      security-events: write
    env:
      BUILDKIT_STEP_LOG_MAX_SIZE: 50000000
      BUILDKIT_STEP_LOG_MAX_SPEED: 10000000
      DOCKER_TMPDIR: "/mnt/docker/docker-tmp"
    steps:
    - name: "OS-Configuration: Preparation: Harden Runner"
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit
    - name: "Preparation: Repository Checkout"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: "Build: gRPC"
      working-directory: "${{ workspace }}/gRPC"
      run: 
        ./compile.sh

    - name: 'upload gRpc binaries'
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: grpc-bin
        path: '${{ workspace }}/gRPC/build/*'

    - name: "Build: launcher"
      working-directory: "${{ workspace }}/launcher"
      run: 
        go build -a -o manager cmd/main.go
    - name: 'upload launcher binaries'
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: grpc-bin
        path: '${{ workspace }}/launcher/manager'
    
