name: Coverity scan
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run scans on'
        default: 'main'
        type: string

permissions:
  contents: read
env:
  COVERITY_PROJECT: 'Intel-Tiber-Broadcast-Suite'
  COVERITY_EMAIL: ${{ secrets.COVERITY_SCAN_EMAIL }}
  COVERITY_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
  DESCRIPTION: ${{ github.ref_name }}
  VERSION: ${{ github.sha }} 
jobs:
  build:
      name: 'coverity'
      runs-on: ubuntu-latest
      timeout-minutes: 90
      steps:
        - name: 'setup: cleanup worskpace'
          run: |
            ls -la ./
            rm -rf ./* || true
            rm -rf ./.??* || true
            ls -la ./

        - name: 'setup: checkout repo'
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
            ref: ${{ inputs.branch }} 
        - name: install coverity tools for cpp and golang
          run: |
            export LANGUAGE=cxx
            .github/coverity/install_coverity.sh
            export LANGUAGE=other
            .github/coverity/install_coverity.sh
          
        - name: 'coverity: build code'
          run: .github/coverity/cov-build.sh all

        - name: 'Handle failure: add fix comment, commit, and create PR'
          if: failure() && github.event_name == 'push'
          run: .github/coverity/fix.sh

        - name: 'coverity: server upload'
          if: github.event_name == 'schedule'
          run: .github/coverity/cov-analysis.sh 
 
        - name: 'coverity: upload raw build artifacts'
          if: github.event_name == 'schedule'
          uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3          
          with:
            name: coverity-scan--details
            path: '${{ github.workspace }}/analysis-details.txt'
