name: Docker Build

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run scans on'
        default: 'main'
        type: string
  pull_request:
  push:
    branches: [ "main" ]


permissions:
  contents: read

env:
  BUILD_TYPE: "Release"
  DOCKER_IMAGE_BASE: "ghcr.io/openvisualcloud/intel-tiber-broadcast-suite"
  DOCKER_IMAGE_NAME: "tiber-broadcast-suite"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"
  DEBIAN_FRONTEND: "noninteractive"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  docker:
    name: "Dockerfile build for Intel® Tiber™ Broadcast Suite"
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    permissions:
      contents: read
      security-events: write
    env:
      BUILDKIT_STEP_LOG_MAX_SIZE: 50000000
      BUILDKIT_STEP_LOG_MAX_SPEED: 10000000
      DOCKER_TMPDIR: "/mnt/docker/docker-tmp"
    steps:
    - name: "OS-Configuration: Preparation: Harden Runner"
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: "OS-Configuration: Report memory, block-dev and free disk space."
      run: |
        sudo free -h
        sudo lsblk
        sudo df -h

    - name: "OS-Configuration: Disable SWAP in OS, create mnt points, show settings."
      shell: bash
      run: |
        export SWAP_FILE="$(sudo swapon --show=NAME | tail -n 1)"
        sudo swapoff "${SWAP_FILE}"
        sudo rm "${SWAP_FILE}"
        sudo mkdir -p "/mnt/docker/docker-d" "/mnt/docker/docker-tmp"

    - name: "OS-Configuration: Add data-root and other JSON changes to dockerd, reload it."
      run: |
        sudo chmod 666 /etc/docker/daemon.json
        echo "$(sudo jq '. += {"data-root":"/mnt/docker/docker-d","log-driver":"json-file","log-format":"text","log-level":"info","log-opts":{"cache-disabled":"false","cache-max-file":"5","cache-max-size":"20m","max-file":"5","max-size":"10m"}}' /etc/docker/daemon.json)" > /etc/docker/daemon.json
        sudo chmod 644 /etc/docker/daemon.json
        sudo systemctl daemon-reload
        sudo systemctl restart docker
        sudo cat "/etc/docker/daemon.json"

    - name: "Configuration: Docker with Buildx Toolkit set up"
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      with:
        buildkitd-flags: "--debug --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host"
        platforms: "linux/amd64"
        driver-opts: memory=14Gib,memory-swap=25Gib,env.BUILDKIT_STEP_LOG_MAX_SIZE=50000000,env.BUILDKIT_STEP_LOG_MAX_SPEED=10000000
        
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        ref: ${{ inputs.branch }}

    - name: "validate build.sh script"
      run: ./build.sh
      env:
        BUILD_TYPE: "CI"
