name: Trivy for Intel® Tiber™ Broadcast Suite
on:
  push:
  workflow_call:
  workflow_dispatch:
    branches: [main]

env:
  BUILD_TYPE: "Release"
  DOCKER_IMAGE_NAME: "docker.io/ovc/tiber-broadcast-suite"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"
  DEBIAN_FRONTEND: "noninteractive"

permissions:
  contents: read

jobs:
  checkout_code:
    name: "Node Preparations for Intel® Tiber™ Broadcast Suite"
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

  trivy-code-scan:
    name: "Code-Scan for Intel® Tiber™ Broadcast Suite"
    runs-on: ubuntu-22.04
    needs: checkout_code
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Run Trivy 'config' type vulnerability scanner.
      uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d # v0.22.0
      with:
        scan-type: 'config'
        hide-progress: false
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-config-tiber-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3.25.8
      with:
        sarif_file: 'trivy-config-tiber-results.sarif'

  trivy-fs-scan:
    name: "Code-FS-Scan for Intel® Tiber™ Broadcast Suite"
    runs-on: ubuntu-22.04
    needs: checkout_code
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Run Trivy 'fs' type vulnerability scanner.
      uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d # v0.22.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-fs-tiber-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3.25.8
      with:
        sarif_file: 'trivy-fs-tiber-results.sarif'
